Release v0.9.0
databio/bedhost pull request #159
Opened 2024-11-26 17:57 UTC by khoroshevskyi

## Changes:
-

2024-12-20 18:05 UTC, nleroy917 requested changes
Lots to go through... I did the best I could. I trust the CSS changes look ok and make sense, so I was just focused more on logic, TypeScript, and python stuff

2024-12-20 18:05 UTC, nleroy917 commented on ui/src/components/modals/create-bedset-modal.tsx
> +  };
Bigger discussion than a PR review, but we probably eventually want to convert this to a `useMutation` implementation. Also, can anyone submit a bedset?

2024-12-20 18:05 UTC, nleroy917 commented on ui/src/components/modals/create-bedset-modal.tsx
> +      </Modal.Body>
Maybe remove this second modal body component?

2024-12-20 18:05 UTC, nleroy917 commented on ui/src/queries/useBedSetBedfiles.ts
> +    gcTime: 30 * 60 * 1000, // This replaces cacheTime in newer versions
Did Chat think this is a good idea, or do we think its a good idea? Do we want to mess with these settings?

2024-12-20 18:05 UTC, nleroy917 commented on ui/src/queries/useBedsetMetadata.ts
> +    gcTime: 30 * 60 * 1000, // This replaces cacheTime in newer versions
Same here

2025-01-03 17:01 UTC, khoroshevskyi commented on bedhost/routers/bed_api.py
> +            pass
its fine, because we expect it to fail if it doesn't exist

2025-01-03 17:01 UTC, khoroshevskyi commented on bedhost/routers/bedset_api.py
> +    "/create/",
no, it works fine, but fixed it

2025-01-03 17:03 UTC, khoroshevskyi commented on bedhost/routers/bedset_api.py
> +    if project_reg_path.namespace not in ["databio", "bedbase", "pepkit"]:
It is work in progress, so I will leave it like this for now

2025-01-03 17:39 UTC, merged